# Generated by Django 6.0.7 on 2026-07-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='awards_certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_certificates',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, default='English, Hindi', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_license',
            field=models.FileField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='online_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='secondary_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_doctors', to='doctors.specialization'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='services_offered',
            field=models.TextField(blank=True, default='General Consultation, Health Checkup, Follow-up'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, default='Mumbai', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
