# Generated by Django 6.0.7 on 2026-07-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=20),
        ),
    ]
